### ISSUE TITLE
Could not install from pip

### ISSUE THREAD

**Issue by zpz** [lbryio/lbry-rocksdb#7]
$ pip install lbry-rocksdb
ERROR: Could not find a version that satisfies the requirement lbry-rocksdb (from versions: none)
ERROR: No matching distribution found for lbry-rocksdb

I'm in a python 3.8 environment. Other packages are fine. I don't know what's the issue.

**Comment by zpz** [comment]
This is on my LinuxMint box. The issue continues. On my Mac laptop within a docker container, it works fine. Almost sure this issue is a machine issue.

**Comment by kevinkjt2000** [comment]
LinuxMint 20.x is based on Ubuntu Focal and the compatibility matrix<sup>1</sup> for manylinux shows that Ubuntu 20 works with manylinux2010 and manylinux2014. However, the [only binary versions available](https://pypi.org/project/lbry-rocksdb/0.8.2/#files) are manylinux_2_24 which would require Ubuntu 21.

I did attempt to help with that https://github.com/twmht/python-rocksdb/commit/9c8db1ee5b44f2a06831a2d599930d10c101f781
but it seems to have been backed out https://github.com/twmht/python-rocksdb/commit/2ea14aee634beb5e2bc5f306086ceee41838e281

Probably the ideal solution is to publish both versions.

1. Manylinux Compatibility Matrix ![image](https://user-images.githubusercontent.com/4098674/170533732-b4309b23-25cb-4552-a8fa-504ece963bab.png)

**Comment by zpz** [comment]
I updated pip to the latest version both on my machine and in my docker. In docker I'm using Ubuntu 20.04. python 3.8. now it works both inside and outside docker.

**Comment by zpz** [comment]
The latest pip as of now is 22.1.1 previously I was using  maybe 20.xx.
